# functions.py - autogenerated for NODE_CATALOG
# Each function: func(inputs: dict, params: dict) -> dict(outputs)
import os, json, math, time, socket, traceback, subprocess
from typing import Dict, Any

def _safe_get(d: dict, key: str, default=None):
    """
    Return d[key] if present and not None, else default.
    Treats explicit None as "missing" so callers that pass defaults get them.
    """
    if not isinstance(d, dict):
        return default
    # Use get but treat None as missing
    v = d.get(key, None)
    if v is None:
        return default
    return v

def _coerce_number(v, default=0.0):
    try:
        return float(v)
    except Exception:
        try:
            return float(str(v).strip())
        except Exception:
            return default
def _coerce_int(v, default=0):
    try: return int(v)
    except Exception: return default
def _coerce_bool(v, default=False):
    if v is None: return default
    if isinstance(v, bool): return v
    s=str(v).strip().lower()
    if s in ('1','true','yes','y','t'): return True
    if s in ('0','false','no','n','f'): return False
    return default
def _json_safe_load(s):
    if s is None: return None
    if isinstance(s,(dict,list)): return s
    try: return json.loads(s)
    except Exception: return None
def _repr(v, maxlen=60):
    try:
        s = json.dumps(v, ensure_ascii=False)
    except Exception:
        s = str(v)
    if len(s)>maxlen: return s[:maxlen-1]+'…'
    return s

functions = {}

def register(fid):
    def deco(fn):
        functions[fid] = fn
        return fn
    return deco

@register('trigger_start')
def trigger_start(inputs, params):
    return {'Exec': True}

@register('trigger_schedule')
def trigger_schedule(inputs, params):
    return {'Exec': True, 'Timestamp': time.strftime('%Y-%m-%d %H:%M:%S')}

@register('trigger_webhook')
def trigger_webhook(inputs, params):
    return {'Exec': True, 'Payload': _safe_get(inputs,'Payload',''), 'Headers': _safe_get(inputs,'Headers','')}

@register('trigger_file')
def trigger_file(inputs, params):
    return {'Exec': True, 'Path': params.get('path',''), 'Event': 'modified'}

@register('trigger_interval')
def trigger_interval(inputs, params):
    return {'Tick': True, 'Count': int(params.get('max_ticks',0))}

@register('trigger_email_in')
def trigger_email_in(inputs, params):
    return {'Exec': True, 'From': _safe_get(inputs,'From',''), 'Subject': _safe_get(inputs,'Subject','')}

@register('trigger_hotkey')
def trigger_hotkey(inputs, params):
    return {'Exec': True, 'Keys': params.get('keys','')}

@register('cond_if')
def cond_if(inputs, params):
    c = _safe_get(inputs,'Condition', params.get('value', False))
    if _coerce_bool(c):
        return {'Vrai': True}
    return {'Faux': True}

@register('cond_compare')
def cond_compare(inputs, params):
    a = _safe_get(inputs,'A',None)
    b = _safe_get(inputs,'B',None)
    op = params.get('op','==')
    try:
        if op in ('==','equals'):
            r = (str(a)==str(b))
        elif op in ('!=','<>'):
            r = (str(a)!=str(b))
        else:
            # best-effort numeric compare
            ra = _coerce_number(a, None)
            rb = _coerce_number(b, None)
            if ra is None or rb is None:
                r = False
            else:
                if op == '>': r = ra > rb
                elif op == '<': r = ra < rb
                elif op == '>=': r = ra >= rb
                elif op == '<=': r = ra <= rb
                else:
                    r = False
    except Exception:
        r = False
    return {'Résultat': r}

@register('cond_filter')
def cond_filter(inputs, params):
    lst = _safe_get(inputs,'Liste', [])
    pred = params.get('predicate')
    if not isinstance(lst, list): lst = [lst]
    if not pred:
        return {'Liste': lst, 'Nb': len(lst)}
    try:
        out = [x for x in lst if eval(pred, {}, {'x': x})]
        return {'Liste': out, 'Nb': len(out)}
    except Exception as e:
        return {'Liste': None, 'Erreur': str(e)}

@register('cond_switch')
def cond_switch(inputs, params):
    key = _safe_get(inputs,'Key', None)
    cases = params.get('cases', {})
    return {'Match': cases.get(str(key))}

@register('cond_and')
def cond_and(inputs, params):
    a = _coerce_bool(_safe_get(inputs,'A', None), False)
    b = _coerce_bool(_safe_get(inputs,'B', None), False)
    return {'Résultat': bool(a and b)}

@register('cond_or')
def cond_or(inputs, params):
    a = _coerce_bool(_safe_get(inputs,'A', None), False)
    b = _coerce_bool(_safe_get(inputs,'B', None), False)
    return {'Résultat': bool(a or b)}

@register('cond_not')
def cond_not(inputs, params):
    v = _coerce_bool(_safe_get(inputs,'Value', None), False)
    return {'Résultat': not v}

@register('flow_loop')
def flow_loop(inputs, params):
    start = int(params.get('start',0)); end = int(params.get('end',0)); step = int(params.get('step',1))
    seq = list(range(start, end, step))
    return {'Items': seq, 'Count': len(seq)}

@register('flow_foreach')
def flow_foreach(inputs, params):
    lst = _safe_get(inputs,'Liste', [])
    if not isinstance(lst, list): lst = [lst]
    return {'Items': lst, 'Count': len(lst)}

@register('flow_while')
def flow_while(inputs, params):
    # stub: returns empty. Implement host-specific iteration logic if needed.
    return {}

@register('flow_trycatch')
def flow_trycatch(inputs, params):
    # stub: pass-through
    return {}

@register('flow_parallel')
def flow_parallel(inputs, params):
    # stub: concurrency must be handled by host — here we return inputs
    return {'Result': inputs}

@register('flow_gate')
def flow_gate(inputs, params):
    # gate toggling handled in host; this stub returns open/closed state
    return {'Open': bool(params.get('open', True))}

@register('tf_calc')
def tf_calc(inputs, params):
    a = _coerce_number(_safe_get(inputs,'A',0)); b = _coerce_number(_safe_get(inputs,'B',0)); op = params.get('op','+')
    try:
        if op == '+': r = a+b
        elif op == '-': r = a-b
        elif op in ('*','×'): r = a*b
        elif op in ('/','÷'): r = (a/b) if b!=0 else None
        else: r = None
    except Exception:
        r = None
    return {'Résultat': r}

@register('tf_json_parse')
def tf_json_parse(inputs, params):
    js = _safe_get(inputs,'JSON', None)
    return {'Objet': _json_safe_load(js)}

@register('tf_format')
def tf_format(inputs, params):
    template = params.get('template','')
    try:
        vals = list(inputs.values())
        out = template.format(*vals, **params)
    except Exception:
        try:
            out = template.format(**params)
        except Exception as e:
            out = None
    return {'Résultat': out}

@register('tf_split')
def tf_split(inputs, params):
    txt = _safe_get(inputs,'Texte',''); sep = params.get('sep',',')
    lst = str(txt).split(sep)
    return {'Liste': lst, 'Nb': len(lst)}

@register('tf_replace')
def tf_replace(inputs, params):
    txt = _safe_get(inputs,'Texte',''); find = _safe_get(inputs,'Chercher',''); repl = _safe_get(inputs,'Remplacer','')
    try:
        return {'Résultat': str(txt).replace(str(find), str(repl))}
    except Exception as e:
        return {'Erreur': str(e)}

@register('tf_b64')
def tf_b64(inputs, params):
    import base64
    mode = params.get('mode','encode').lower(); data = _safe_get(inputs,'Données','')
    try:
        if mode.startswith('enc'):
            return {'Résultat': base64.b64encode(str(data).encode()).decode()}
        else:
            return {'Résultat': base64.b64decode(str(data)).decode('utf-8','ignore')}
    except Exception as e:
        return {'Erreur': str(e)}

@register('var_string')
def var_string(inputs, params):
    # Try connected input first, fallback to params['value'], return None as None (not string "None")
    v = _safe_get(inputs, "Valeur", None)
    if v is None:
        v = params.get("value", "")
    return {"Résultat": v}

@register('var_number')
def var_number(inputs, params):
    v = _safe_get(inputs, "Valeur", None)
    if v is None:
        v = params.get("value", 0.0)
    return {"Résultat": _coerce_number(v, 0.0)}

@register('var_bool')
def var_bool(inputs, params):
    v = _safe_get(inputs, "Valeur", None)
    if v is None:
        v = params.get("value", False)
    return {"Résultat": _coerce_number(v, 0.0)}

@register('var_const')
def var_const(inputs, params):
    v = params.get('value', None)
    return {'Valeur': v}

@register('var_env')
def var_env(inputs, params):
    name = params.get('var_name',''); default = params.get('default','')
    return {'Valeur': os.environ.get(name, default)}

@register('sys_info')
def sys_info(inputs, params):
    import platform
    return {'platform': platform.platform(), 'machine': platform.machine(), 'node': platform.node()}

@register('sys_path')
def sys_path(inputs, params):
    # Implement basic file ops via action_read_file / action_write_file mapping
    op = params.get('op','stat')
    path = _safe_get(inputs,'Chemin', params.get('path',''))
    try:
        if op == 'stat':
            return {'exists': os.path.exists(path)}
        elif op == 'mkdir':
            os.makedirs(path, exist_ok=True)
            return {'Succès': True}
        elif op == 'listdir':
            return {'Items': os.listdir(path)}
        elif op == 'remove':
            os.remove(path)
            return {'Succès': True}
        else:
            return {'Erreur': 'Unknown op'}
    except Exception as e:
        return {'Erreur': str(e)}

@register('sys_proc')
def sys_proc(inputs, params):
    # caution: do not execute arbitrary commands without checking security
    cmd = _safe_get(inputs,'Cmd', params.get('cmd',''))
    if not cmd:
        return {'Succès': False, 'Erreur': 'No command'}
    # For safety we return not implemented — host can extend this
    return {'Succès': False, 'Erreur': 'sys_proc execution disabled in default functions.py'}

@register('net_dns')
def net_dns(inputs, params):
    host = _safe_get(inputs,'Host', params.get('host',''))
    try:
        ip = socket.gethostbyname(host)
        return {'IP': ip}
    except Exception as e:
        return {'Erreur': str(e)}

@register('net_ping')
def net_ping(inputs, params):
    host = _safe_get(inputs,'Host', params.get('host',''))
    port = int(params.get('port', 80) or 80)
    try:
        start = time.time(); s=socket.create_connection((host, port), timeout=3); s.close(); r = (time.time()-start)
        return {'Alive': True, 'RTT': r}
    except Exception as e:
        return {'Alive': False, 'Erreur': str(e)}

@register('net_ftp')
def net_ftp(inputs, params):
    # stub: FTP/SFTP needs paramiko/ftplib — implement in host if needed
    return {'Succès': False, 'Erreur': 'FTP not implemented in functions.py'}

@register('net_mqtt')
def net_mqtt(inputs, params):
    # stub: MQTT requires paho-mqtt — implement in host if needed
    return {'Succès': False, 'Erreur': 'MQTT not implemented in functions.py'}

@register('out_log')
def out_log(inputs, params):
    msg = _safe_get(inputs,'Message','')
    print('[LOG]', _repr(msg))
    return {}

@register('out_end')
def out_end(inputs, params):
    return {'ExitCode': int(params.get('exit_code',0))}

@register('out_ui_dialog')
def out_ui_dialog(inputs, params):
    msg = _safe_get(inputs,'Message', params.get('message',''))
    return {'OK': True, 'Réponse': str(msg)}

@register('out_webhook')
def out_webhook(inputs, params):
    # host should actually perform HTTP calls; we return a stub success
    return {'Sent': True}

@register('action_write_file')
def action_write_file(inputs, params):
    path = _safe_get(inputs, 'Chemin', params.get('path', None))
    content = _safe_get(inputs, 'Contenu', params.get('content', ''))
    # If content is None, write empty string
    if content is None:
        content = ""
    mode_param = params.get('mode', 'Écraser')
    encoding = params.get('encoding', 'UTF-8') or 'UTF-8'
    create_dirs = _coerce_bool(params.get('create_dirs', True), True)

    if isinstance(path, str) and path.strip().lower() == "none":
        path = None
    if not path:
        return {'Succès': False, 'Erreur': 'No path'}

    try:
        d = os.path.dirname(path)
        if d and create_dirs and not os.path.exists(d):
            os.makedirs(d, exist_ok=True)

        if mode_param == 'Ajouter':
            open_mode = 'a'
        elif mode_param == 'Créer uniquement':
            if os.path.exists(path):
                return {'Succès': False, 'Erreur': 'File exists'}
            open_mode = 'w'
        else:
            open_mode = 'w'

        with open(path, open_mode, encoding=encoding) as fh:
            fh.write(str(content))
        return {'Succès': True}
    except PermissionError as pe:
        return {'Succès': False, 'Erreur': f'Permission denied: {pe}'}
    except Exception as e:
        return {'Succès': False, 'Erreur': str(e)}

@register('action_read_file')
def action_read_file(inputs, params):
    path = _safe_get(inputs,'Chemin', params.get('path',''))
    try:
        with open(path,'r', encoding='utf-8') as fh: data = fh.read()
        return {'Contenu': data}
    except Exception as e:
        return {'Erreur': str(e)}

@register('action_email')
def action_email(inputs, params):
    # sending email requires SMTP configuration — host should implement
    return {'Succès': False, 'Erreur': 'action_email not implemented (configure SMTP in host)'}

@register('action_http')
def action_http(inputs, params):
    """
    HTTP request node backend using urllib (no external deps)

    Inputs possibles:
        URL
        Body

    Params possibles:
        method   -> GET / POST / PUT / PATCH / DELETE
        headers  -> JSON string ou dict
        timeout  -> seconds
    """

    import urllib.request
    import urllib.error
    import urllib.parse
    import json

    url = _safe_get(inputs, "URL", params.get("url"))
    body = _safe_get(inputs, "Body", params.get("body"))
    method = str(params.get("method", "GET")).upper()
    timeout = float(params.get("timeout", 30))

    # headers peuvent être JSON string
    headers = params.get("headers", {})
    if isinstance(headers, str):
        try:
            headers = json.loads(headers)
        except Exception:
            headers = {}

    if not url:
        return {"Succès": False, "Erreur": "URL manquante"}

    try:
        data = None

        if method in ("POST", "PUT", "PATCH", "DELETE"):
            if isinstance(body, (dict, list)):
                data = json.dumps(body).encode("utf-8")
                headers.setdefault("Content-Type", "application/json")
            elif body is not None:
                data = str(body).encode("utf-8")

        req = urllib.request.Request(
            url=url,
            data=data,
            headers=headers,
            method=method
        )

        with urllib.request.urlopen(req, timeout=timeout) as resp:
            status = resp.getcode()
            raw = resp.read()

            try:
                text = raw.decode("utf-8")
            except:
                text = raw.decode("latin-1", errors="ignore")

        return {
            "Succès": True,
            "Code": status,
            "Réponse": text
        }

    except urllib.error.HTTPError as e:
        return {
            "Succès": False,
            "Code": e.code,
            "Erreur": str(e)
        }

    except urllib.error.URLError as e:
        return {
            "Succès": False,
            "Erreur": str(e.reason)
        }

    except Exception as e:
        return {
            "Succès": False,
            "Erreur": str(e)
        }

@register('action_notification')
def action_notification(inputs, params):
    msg = _safe_get(inputs,'Message', params.get('message',''))
    return {'OK': True, 'Réponse': str(msg)}

@register('double_inputs')
def double_inputs(inputs, params):
    a = _safe_get(inputs, "A", params.get("a", 0))
    try:
        return {"Result": _coerce_number(a, 0.0) * 2}
    except Exception:
        return {"Result": None}

@register('concat_inputs')
def concat_inputs(inputs, params):
    left = _safe_get(inputs, "Left", "")
    right = _safe_get(inputs, "Right", "")
    return {"Out": f"{left}{right}"}


def register_functions():
    return functions